[build]
    base = "."
    command = "npm run build"
    publish =  "dist/www"
    functions = "src/app/functions"

[dev]
  ## TODO: remove yarn dep
  command = "npx yarn develop"
  port = 3334
  publish = "dist/www"