[build]
    base = "."
    command = "npm run build"
    publish =  "dist/www"
    functions = "src/app/functions"

[dev]
  ## TODO: remove yarn dep
  command = "yarn develop"
  port = 3333
  publish = "dist/www"