/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface AppRoot {}
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'AppRoot': Components.AppRoot;
  }

  interface IntrinsicElements {
    'AppRoot': LocalJSX.AppRoot;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
}

