/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface PeidDesignSystem {}
}

declare namespace LocalJSX {
  interface PeidDesignSystem extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'PeidDesignSystem': Components.PeidDesignSystem;
  }

  interface IntrinsicElements {
    'PeidDesignSystem': LocalJSX.PeidDesignSystem;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLPeidDesignSystemElement extends Components.PeidDesignSystem, HTMLStencilElement {}
  var HTMLPeidDesignSystemElement: {
    prototype: HTMLPeidDesignSystemElement;
    new (): HTMLPeidDesignSystemElement;
  };
  interface HTMLElementTagNameMap {
    'peid-design-system': HTMLPeidDesignSystemElement
  }

  interface ElementTagNameMap {
    'peid-design-system': HTMLPeidDesignSystemElement;
  }
}

