/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {
  interface PeidCard {}
  interface PeidHero {
    /**
    * The current title of the page
    */
    'title': string;
  }
  interface PeidHomepage {}
  interface PeidImg {
    /**
    * The alt text to display if the image does not load
    */
    'alt': string;
    /**
    * The physical height of the image
    */
    'height': number;
    /**
    * The primary color of the image (hex)
    */
    'primaryColor': string;
    /**
    * The URL or path to the image
    */
    'src': string;
    /**
    * A responsive srcset for this image
    */
    'srcset': string;
    /**
    * The physical width of the image
    */
    'width': number;
  }
  interface PeidLogo {}
  interface PeidPageNotFound {
    'match': MatchResults;
  }
  interface PeidWebsite {}
}

declare namespace LocalJSX {
  interface PeidCard extends JSXBase.HTMLAttributes {}
  interface PeidHero extends JSXBase.HTMLAttributes {
    /**
    * The current title of the page
    */
    'title'?: string;
  }
  interface PeidHomepage extends JSXBase.HTMLAttributes {}
  interface PeidImg extends JSXBase.HTMLAttributes {
    /**
    * The alt text to display if the image does not load
    */
    'alt'?: string;
    /**
    * The physical height of the image
    */
    'height'?: number;
    /**
    * The primary color of the image (hex)
    */
    'primaryColor'?: string;
    /**
    * The URL or path to the image
    */
    'src'?: string;
    /**
    * A responsive srcset for this image
    */
    'srcset'?: string;
    /**
    * The physical width of the image
    */
    'width'?: number;
  }
  interface PeidLogo extends JSXBase.HTMLAttributes {}
  interface PeidPageNotFound extends JSXBase.HTMLAttributes {
    'match'?: MatchResults;
  }
  interface PeidWebsite extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'PeidCard': Components.PeidCard;
    'PeidHero': Components.PeidHero;
    'PeidHomepage': Components.PeidHomepage;
    'PeidImg': Components.PeidImg;
    'PeidLogo': Components.PeidLogo;
    'PeidPageNotFound': Components.PeidPageNotFound;
    'PeidWebsite': Components.PeidWebsite;
  }

  interface IntrinsicElements {
    'PeidCard': LocalJSX.PeidCard;
    'PeidHero': LocalJSX.PeidHero;
    'PeidHomepage': LocalJSX.PeidHomepage;
    'PeidImg': LocalJSX.PeidImg;
    'PeidLogo': LocalJSX.PeidLogo;
    'PeidPageNotFound': LocalJSX.PeidPageNotFound;
    'PeidWebsite': LocalJSX.PeidWebsite;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLPeidCardElement extends Components.PeidCard, HTMLStencilElement {}
  var HTMLPeidCardElement: {
    prototype: HTMLPeidCardElement;
    new (): HTMLPeidCardElement;
  };

  interface HTMLPeidHeroElement extends Components.PeidHero, HTMLStencilElement {}
  var HTMLPeidHeroElement: {
    prototype: HTMLPeidHeroElement;
    new (): HTMLPeidHeroElement;
  };

  interface HTMLPeidHomepageElement extends Components.PeidHomepage, HTMLStencilElement {}
  var HTMLPeidHomepageElement: {
    prototype: HTMLPeidHomepageElement;
    new (): HTMLPeidHomepageElement;
  };

  interface HTMLPeidImgElement extends Components.PeidImg, HTMLStencilElement {}
  var HTMLPeidImgElement: {
    prototype: HTMLPeidImgElement;
    new (): HTMLPeidImgElement;
  };

  interface HTMLPeidLogoElement extends Components.PeidLogo, HTMLStencilElement {}
  var HTMLPeidLogoElement: {
    prototype: HTMLPeidLogoElement;
    new (): HTMLPeidLogoElement;
  };

  interface HTMLPeidPageNotFoundElement extends Components.PeidPageNotFound, HTMLStencilElement {}
  var HTMLPeidPageNotFoundElement: {
    prototype: HTMLPeidPageNotFoundElement;
    new (): HTMLPeidPageNotFoundElement;
  };

  interface HTMLPeidWebsiteElement extends Components.PeidWebsite, HTMLStencilElement {}
  var HTMLPeidWebsiteElement: {
    prototype: HTMLPeidWebsiteElement;
    new (): HTMLPeidWebsiteElement;
  };
  interface HTMLElementTagNameMap {
    'peid-card': HTMLPeidCardElement
    'peid-hero': HTMLPeidHeroElement
    'peid-homepage': HTMLPeidHomepageElement
    'peid-img': HTMLPeidImgElement
    'peid-logo': HTMLPeidLogoElement
    'peid-page-not-found': HTMLPeidPageNotFoundElement
    'peid-website': HTMLPeidWebsiteElement
  }

  interface ElementTagNameMap {
    'peid-card': HTMLPeidCardElement;
    'peid-hero': HTMLPeidHeroElement;
    'peid-homepage': HTMLPeidHomepageElement;
    'peid-img': HTMLPeidImgElement;
    'peid-logo': HTMLPeidLogoElement;
    'peid-page-not-found': HTMLPeidPageNotFoundElement;
    'peid-website': HTMLPeidWebsiteElement;
  }
}

