/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {
  interface PeidHero {
    /**
    * The current title of the page
    */
    'heading': string;
  }
  interface PeidPageHome {}
  interface PeidPageNotFound {
    'match': MatchResults;
  }
  interface PeidPagePost {
    'url': string;
  }
  interface PeidWebsite {}
  interface PeidWebsiteRouter {}
}

declare global {


  interface HTMLPeidHeroElement extends Components.PeidHero, HTMLStencilElement {}
  var HTMLPeidHeroElement: {
    prototype: HTMLPeidHeroElement;
    new (): HTMLPeidHeroElement;
  };

  interface HTMLPeidPageHomeElement extends Components.PeidPageHome, HTMLStencilElement {}
  var HTMLPeidPageHomeElement: {
    prototype: HTMLPeidPageHomeElement;
    new (): HTMLPeidPageHomeElement;
  };

  interface HTMLPeidPageNotFoundElement extends Components.PeidPageNotFound, HTMLStencilElement {}
  var HTMLPeidPageNotFoundElement: {
    prototype: HTMLPeidPageNotFoundElement;
    new (): HTMLPeidPageNotFoundElement;
  };

  interface HTMLPeidPagePostElement extends Components.PeidPagePost, HTMLStencilElement {}
  var HTMLPeidPagePostElement: {
    prototype: HTMLPeidPagePostElement;
    new (): HTMLPeidPagePostElement;
  };

  interface HTMLPeidWebsiteElement extends Components.PeidWebsite, HTMLStencilElement {}
  var HTMLPeidWebsiteElement: {
    prototype: HTMLPeidWebsiteElement;
    new (): HTMLPeidWebsiteElement;
  };

  interface HTMLPeidWebsiteRouterElement extends Components.PeidWebsiteRouter, HTMLStencilElement {}
  var HTMLPeidWebsiteRouterElement: {
    prototype: HTMLPeidWebsiteRouterElement;
    new (): HTMLPeidWebsiteRouterElement;
  };
  interface HTMLElementTagNameMap {
    'peid-hero': HTMLPeidHeroElement;
    'peid-page-home': HTMLPeidPageHomeElement;
    'peid-page-not-found': HTMLPeidPageNotFoundElement;
    'peid-page-post': HTMLPeidPagePostElement;
    'peid-website': HTMLPeidWebsiteElement;
    'peid-website-router': HTMLPeidWebsiteRouterElement;
  }
}

declare namespace LocalJSX {
  interface PeidHero extends JSXBase.HTMLAttributes<HTMLPeidHeroElement> {
    /**
    * The current title of the page
    */
    'heading'?: string;
  }
  interface PeidPageHome extends JSXBase.HTMLAttributes<HTMLPeidPageHomeElement> {}
  interface PeidPageNotFound extends JSXBase.HTMLAttributes<HTMLPeidPageNotFoundElement> {
    'match'?: MatchResults;
  }
  interface PeidPagePost extends JSXBase.HTMLAttributes<HTMLPeidPagePostElement> {
    'url'?: string;
  }
  interface PeidWebsite extends JSXBase.HTMLAttributes<HTMLPeidWebsiteElement> {}
  interface PeidWebsiteRouter extends JSXBase.HTMLAttributes<HTMLPeidWebsiteRouterElement> {}

  interface IntrinsicElements {
    'peid-hero': PeidHero;
    'peid-page-home': PeidPageHome;
    'peid-page-not-found': PeidPageNotFound;
    'peid-page-post': PeidPagePost;
    'peid-website': PeidWebsite;
    'peid-website-router': PeidWebsiteRouter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


